### ISSUE TITLE
Spatially dependent mannings coefficient fails with Nan Flux 

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/ats#106]
We create a mesh with two face sets on the surface to define regions that are then used to define spatially dependent mannings coefficient.  This is based on the Borden test case, with a simple rainfall event.   The simulation runs if mannings coefficient is defined in the usual way as homogenous over the whole surface.  We also tested the regions defined by the two face sets to set a spatially dependent rainfall (different constant over each region).  So we are reasonably confident that the face sets themselves, and resulting regions, are well defined.

An input file and mesh file are on
[Google Drive](https://drive.google.com/drive/folders/1p5zsdYpcq79ZqCaGj2fAbJw6hexNmwd0?usp=sharing)

Note: I understand this is a crappy location, but issues don't allow these files to be attached (hard to believe I know).

**Comment by hydro-geomorph-zhang** [comment]
We tested the Borden case simulation with three subsurface layers with different permeability. The first run showed Nan fluxes with a critical depth boundary condition. Then, David suggested making sure a non-zero value for the epsilon coefficient to avoid a zero slope. It did solve the nan flux problem. 

The second run was to add different manning's coefficients on the land surface mesh to represent surface heterogeneity. I made up a simple land cover data with only two land cover types to generate two different regions (or facesets). I tried to apply two different rainfall on the two regions with homogeneous manning's N. There is no problem in the simulation, which means that the definition of the two surface regions is correct. 

However, after I assigned two different manning's N values on the two regions, the simulation showed an error message "Overland Conductivity Evaluator: Manning coeficient has at least one value that is non-positive.  Perhaps you forgot to set the "boundary_face" component?". Apparently, we added boundary_face when we define each manning's N value. Do you think there is anything we missed?

**Comment by ecoon** [comment]
> FYI, Amanzi has a few tools that helped me tremendously in code debugging. One is the i/o capability State::WriteStateStatistics(S, vo). The other one is mesh region analysis, see Amanzi::InputAnalysis class.
> You may consider using them in ATS.

We do use WriteStateStatistics() now, but I'm not familiar with InputAnalysis.  Can you give a short description of this, or is it documented somewhere?  I don't see any description of what it is doing in the code.

**Comment by ecoon** [comment]
working on this now on branch ecoon/ism_refactor

**Comment by ecoon** [comment]
Can @jd-moulton  re-check this on Amanzi branch master and ATS branch ecoon/ism_refactor?  I hope it should work now.

**Comment by ecoon** [comment]
that branch is merged into master now, so @jd-moulton and @pinshuai this could be checked on master now.  I believe it should work -- feel free to reopen this ticket if you have more trouble.
