### ISSUE TITLE
Henry problem regression test is failing

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#114]
I’m trying to do some refactoring work, and am updating tests.  The Henry problem is not currently passing on master.

At first glance, the comparison fails because, in master, “total_component_concentration” does not have a “boundary_face” component under master, but it did in a previous version of the code.   I’m not entirely sure what would have changed that.  It seems likely that there _should_ be a boundary_face component, since I know we need density on the boundary faces, and that is calculated from concentration, and therefore we should have boundary face quantities for TCC.

Then, if I turn off the test for TCC boundary faces and only check cells, then I see that (not surprisingly probably) the answer is off by a bit (~10%), though qualitatively the answer is similar.  

At second glance, there may be a bug in molar density (and I’m not sure whether that is new or old) – while mass density is as expected (e.g. the salty region in the lower right is denser than the freshwater region), the molar density is the opposite (e.g. the molar density of freshwater is larger than that of saltwater).  Is that right?  See attached image.

Could @dasvyat  or @hydro-geomorph-zhang look into this and try to fix it on master?  I’m looking to do a new release here soon before working on a large set of “state” changes.  Daniil, I will likely need some of your help on those changes too – look for an email to you and Joe B on this soon.  This is to make ATS use a single state + time tags, as we’ve discussed before a long time ago!

**Comment by ecoon** [comment]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/5126139/151444553-af67399b-38cd-4200-996b-d8edc24133cc.png">

**Comment by dasvyat** [comment]
I'll take of it over this weekend

**Comment by dasvyat** [comment]
Name of concentration fields are different in new and old checkpoint files

**Comment by ecoon** [comment]
Was that really it, the suffix on the degree of freedom or something else?  Ok, well, that's an easy fix.  Can you update the test?

python regression_tests.py -u path/to/test.cfg
./clean_test.py path/to/testdir.regression.gold
git commit ...

thanks!

**Comment by dasvyat** [comment]
Gold files are updated

**Comment by ecoon** [comment]
Yeah, it looks to me like the flow solve is a bit different, driving a different front.  This is the difference at checkpoint 40 

![tcc_diff](https://user-images.githubusercontent.com/5126139/153244781-dd027d07-8584-4e07-bbaa-96e7b3d62291.png)

**Comment by ecoon** [comment]
Also, can you confirm that this is right:

      <Parameter name="component molar masses" type="Array(double)" value="{ 1}" />

That seems a bit odd to me -- looks like an ignored dimensionalization, that maybe is important for flow driven by density variations.  But it is also possible that this parameter is ignored or unnecessary for this problem.

**Comment by ecoon** [comment]
So @dasvyat  I'm uncertain what to do here.  The test is a bit unstable because minor changes in flow solve is probably  driving order 1 pointwise differences in TCC.  We could try tightening the tolerance on the flow solve, but I'm not sure how much that will help.  We could try adding some diffusion to avoid the front being so sharp.  Not sure -- any ideas here?

**Comment by dasvyat** [comment]
I'll take a look. Maybe we need to set up fixed time stepping.

**Comment by dasvyat** [comment]
@ecoon I've pushed two branches to ats  - dsv/minor_fixes2transport, and to ats-regression-tests - dsv/seawater_transport.
The main difference is new subfield names for total_component concentration fields. Can you check does it work for you?
