### ISSUE TITLE
Documentation or explanation for smoothing interval width [saturation]

### ISSUE THREAD

**Issue by heglab** [amanzi/ats#120]
The use of "smoothing interval width [saturation]" in wrm-van-genuchten-spec is not clear and there seem to be no explanation or documentation on it. Is it the theta-s (saturated moisture content) that is usually obtained from soil water retention curve (or maybe from some pedotransfer function)?

**Comment by fmyuan** [comment]
No. This refers to the saturation interval from 1.0 (ie fully saturated). From this point to 1.0, van Genutchten retension curve will be spline-liked smoothed for better performance. The spline-liked smoothing would try to avoid over-shooting, which may be cases for normal spline-smoothing. It's also smoothing relative permissivity.  Similarly, you may either set this in capillary pressure, as "saturation smoothing interval [Pa]"  with value >0.0. For "smoothing interval width [saturation]", the valid value shall be less than 1.0

**Comment by heglab** [comment]
> No. This refers to the saturation interval from 1.0 (ie fully saturated). From this point to 1.0, van Genutchten retension curve will be spline-liked smoothed for better performance. The spline-liked smoothing would try to avoid over-shooting, which may be cases for normal spline-smoothing. It's also smoothing relative permissivity. Similarly, you may either set this in capillary pressure, as "saturation smoothing interval [Pa]" with value >0.0. For "smoothing interval width [saturation]", the valid value shall be less than 1.0


Thank you for the explanation. I understand it now.

**Comment by heglab** [comment]
But I still have a clarification about the theta-s (saturated moisture content) that is usually obtained from soil water retention curve (or maybe from some pedotransfer function). I would assume this is the input for the porosity (base porosity) because I would expect the water to fill all the voids available when it becomes saturated. Is it safe to do that because the wrm-van-genuchten-spec does not have an option for theta-s

**Comment by fmyuan** [comment]
You're correct of theta-s. It's indeed base porosity when setting up in input .xml. It's considered independent from ATS's water retention curve.

**Comment by heglab** [comment]
Thanks. I really appreciate
