### ISSUE TITLE
ATS Alquimia usage uses the wrong state

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#129]
Alquimia_PK uses S_ throughout, meaning that, for all chemistry steps, saturation, porosity, density are all the "old" values and not the "new" values.  Unclear what is right.  Transport mostly uses the "new" values, and I would have expected reactions to follow transport's lead.

This is probably only a bug in ATS, not Amanzi, because Amanzi uses only one State and by default the default tag is "new".

Fix in new state!

**Comment by ecoon** [comment]
Note the fix for this to get unit tests to pass will break Amanzi, so this must be fixed (really it is already fixed in comments in Alquimia_PK.cc on konstantin/state, so just ATS's tests have to be updated) prior to merging konstantin/state.

**Comment by lipnikov** [comment]
@ecoon We are solving d(p s C) / dt = Ft + Fc using the operator split. So transport does (p s C)^1/2 - (p s C)^0  / k = Ft and chemistry must match for conservation, i.e.(p s C)^1 - (p s C)^1/2 / k = Fc. Since chemistry uses only one s, we need s^1 = s^1/2. Same for p.

**Comment by ecoon** [comment]
That's what I thought, thanks.

**Comment by ecoon** [comment]
Fixed in state refactor.
