### ISSUE TITLE
Issue in ATS transport diffusion calculation with multiple components

### ISSUE THREAD

**Issue by AndrewGraus** [amanzi/ats#148]
There appears to be an error in how the diffusivity is calculated in ATS transport with multiple components. I've discussed this with @smolins and as I think I've identified the origin of the bug I'm raising this issue. The diffusion for the first component seems normal, however subsequent components diffuse faster than they should, when compared to running that component in isolation. Below are some plots to illustrate the issue. Plotted is the TCC as a function of depth in a single column of a test volume where I am diffusing 3 aqueous components in the two figures the only difference is the ordering of the components, in the first the order is {O2, Ar, N2O} in the second it is {Ar, O2, N2O}.

![ATS_transport](https://user-images.githubusercontent.com/16768799/185706157-2c9078d6-f416-4337-a87c-34072a8360ac.png)

![ATS_transport_reordered](https://user-images.githubusercontent.com/16768799/185706180-d67649d3-dcbb-4228-a01d-19fe3c1c7892.png)

From digging into this issue more the bug seems to be in:

 [https://github.com/amanzi/ats/blob/master/src/pks/transport/transport_ats_pk.cc](url) 

Specifically in the CalculateDiffusionTensor function when computed within the loop at line 995:

```
for (int i = 0; i < num_aqueous; i++) {
      FindDiffusionValue(component_names_[i], &md_new, &phase);
      md_change = md_new - md_old;
      md_old = md_new;

      if (md_change != 0.0) {
        CalculateDiffusionTensor_(md_change, phase, *phi_, *ws_, *mol_dens_);
        flag_op1 = true;
      }
```
If I read this correctly the intention is to only calculate the amount by which the tensor has changed between components. However in the CalculateDiffusionTensor function at lines 91 (97 for a gaseous component) the Dispersion/Diffusion tensor is multiplied by mol_den. This is done for every component, effectively multiplying the 2nd component by mol_den^2, the third by mol_den^3, ect. Below is the input file I used (I had to change the extension to .txt from .xml because github weirdly doesn't let you attach .xml files). I think this issue could be fixed by having the mol_den multiplication be done in the dispersion calculation as that is only done once.

[flat_three.txt](https://github.com/amanzi/ats/files/9385439/flat_three.txt)

**Comment by ecoon** [comment]
@AndrewGraus  sorry Andrew, I flat out missed this.  Thanks for the bug report -- we'll fix this before the next release.

**Comment by ecoon** [comment]
@dasvyat @saubhagya-gatech @jbeisman is one of you available to fix this in the next few days before we release next week?

**Comment by jbeisman** [comment]
I'll dig into this asap.

**Comment by jbeisman** [comment]
@AndrewGraus Thanks for the detailed bug report.  The bug should be fixed once this PR is merged.
