### ISSUE TITLE
Saturated vapor pressure over liquid/ice 

### ISSUE THREAD

**Issue by gaobhub** [amanzi/ats#151]
This work is to define the saturated vapor pressure for above- and below-freezing cases separately. In the meantime, the input file will ask for "surface-vapor_pressure_air" instead of "surface-relative_humidity". Specifically, files that will be affected include:
- Codes under **$ATS_SRC_DIR/src/pks/surface_balance/constitutive_relations/land_cover/**
   1. seb_physics_funcs.cc: use Westermann (2016) to calculate vp_sat instead of Bolton (1980), use vapor pressure and temperature directly to calculate incoming longwave radiation.
   2. seb_physics_funcs.hh
   3. seb_physics_defs.hh: include vp_air in MetData struct
   4. seb_threecomponent_evaluator.cc: requires "surface-vapor_pressure_air" as input
   5. seb_threecomponent_evaluator.hh
   6. seb_twocomponent_evaluator.cc: requires "surface-vapor_pressure_air" as input
   7. seb_twocomponent_evaluator.hh
   8. pet_priestley_taylor_evaluator.cc: use Westermann (2016) to calculate vp_sat in vapor_pressure-temperature slope, no need to ask for "surface-relative_humidity" or "surface-vapor_pressure"
   9. pet_priestley_taylor_evaluator.hh
   10. longwave_evaluator.cc: requires "surface-vapor_pressure_air" as input
   11. longwave_evaluator.hh
- Codes under **$ATS_SRC_DIR/src/pks/surface_balance/CLM/**
   1. ats_clm.F90: calculate spec_q by vp_air and p_atm instead of q_sat*rh
   2. ats_clm_interface.cc: use vp_air and remove rel_hum
   3. ats_clm_interface.hh
   4. ats_clm_interface_private.hh
   5. surface_balance_CLM.cc: requires "surface-vapor_pressure_air" as input
   6. surface_balance_CLM.hh
- Codes under **$ATS_SRC_DIR/src/pks/biogeochemistry/fates/**
   1. fates_pk.cc: requires "surface-vapor_pressure_air" as input, rh24_patch=vp_air/es
   2. fates_pk.hh
- Codes under **$ATS_SRC_DIR/src/pks/biogeochemistry/bgc_simple/**
   1. bgc_simple.cc: requires "surface-vapor_pressure_air" as input
   2. bgc_simple_funcs.cc: use vp_air as a parameter of function Photosynthesis()
   3. utils.hh: include vp_air in MetData struct
   4. vegetation.cc: remove ea = rh*es, use vp_air as a parameter of function Photosynthesis()
   5. vegetation.hh
- Codes under **tools/utils**
   1. daymat_to_ats.py: keep "vp_Pa" from daymet raw data and delete the conversion of vapor pressure to relative humidity.

**Comment by ecoon** [comment]
@gaobhub  Can you also add a script under tools/utils to convert "old" ATS h5 files to "new" ATS h5 files with vp instead of RH?
