### ISSUE TITLE
not able to choose specific compilers

### ISSUE THREAD

**Issue by ddwivedi08** [amanzi/ats#19]
@ecoon 
@jd-moulton 

Please look at the CMakeOutput.log and CMakeErr
[CMakeOutput.log](https://github.com/amanzi/ats/files/3347690/CMakeOutput.log)
[CMakeError.log](https://github.com/amanzi/ats/files/3347691/CMakeError.log)
[CMakeError.log](https://github.com/amanzi/ats/files/3347692/CMakeError.log)
[CMakeOutput.log](https://github.com/amanzi/ats/files/3347693/CMakeOutput.log)

or.log. I think the problem is that GCC compiler and gfortran from anaconda are not compatible. Can you please help?

Thanks,
Dipankar

**Comment by ecoon** [comment]
I'm sorry Dipankar, this slipped through the cracks.  Let me know if it is still an issue.

It looks like the compiler changed between Amanzi and ATS, or that the flags are getting picked up incorrectly.  Is this during configuring Amanzi (i.e. running bootstrap) or during configuring ATS?
