### ISSUE TITLE
Add option for ats to append instead of overwrite simulation output

### ISSUE THREAD

**Issue by pinshuai** [amanzi/ats#22]
I am looking for an option in ATS to append the new results every time when I restart the model from a checkpoint file. The current setting will overwrite the output file by default. The append option would be very useful to keep the output file continuous without cutting the old results.

**Comment by ecoon** [comment]
Hi Pin, this is not currently a capability supported by Amanzi's output routines -- it would have to be supported there first and then could be added as an option here.  I'm closing this for now and would encourage you to open a ticket at github.com/amanzi/amanzi requesting this.

In the meantime, you can run your "continuation" run in a new directory, then merge the two directories into a single .VisIt.xmf file through the script at 

https://github.com/amanzi/ats/blob/master/tools/utils/combine_xmf.py

(and a corresponding one for observations).
