### ISSUE TITLE
tests requiring geochemistry still run when compiling with --disable-geochemistry

### ISSUE THREAD

**Issue by rfiorella** [amanzi/ats#248]
A handful of regression tests (all the 07-* tests, and many of the 09-* tests) fail when using ctest against ATS binary built with --disable-geochemistry. Presumably these test failures are expected since these would be the tests requiring geochemistry, and so perhaps should be disabled when using --disable-geochemistry in bootstrap.

Occurs both building against master and rfiorella/elm_api (1.4) branches. 

(Not sure if this repo or Amanzi is the right place for this issue - let me know if it should be moved).

**Comment by ecoon** [comment]
Yep, this is a fine place.

Fixing this requires two changes:

1. In amanzi/ats-regression-tests, add a new testsuite for "testing_no_geochemistry" that omits the geochemistry tests.
2. In ats's cmake, there is a call to `python regression_tests.py --list-tests --suites=testing` which generates the list of tests to add as ctest targets.  This would need to be updated to get the right suite based on the boolean ENABLE_GEOCHEMISTRY

**Comment by rfiorella** [comment]
Closed by #281 and corresponding PR in regression-tests
