### ISSUE TITLE
issues extracting the groundwater discharge for Coal Creek

### ISSUE THREAD

**Issue by Jihadothman1** [amanzi/ats#258]
Hi, 

Pin Shuai reached out on google group last month asking about the estimation of groundwater discharge for Coal Creek watershed. An approach was suggested which is adding these lines: 

        <ParameterList name="exfiltration [mol d^-1]" type="ParameterList">
          <Parameter name="variable" type="string" value="surface-surface_subsurface_flux" />
          <Parameter name="region" type="string" value="surface domain" />
          <Parameter name="location name" type="string" value="cell" />
          <Parameter name="functional" type="string" value="extensive integral" />
          <Parameter name="time integrated" type="bool" value="true" />
          <ParameterList name="modifier" type="ParameterList">
            <Parameter name="function type" type="string" value="standard math" />
            <Parameter name="operator" type="string" value="positive" />
          </ParameterList>
        </ParameterList>
        <ParameterList name="infiltration [mol d^-1]" type="ParameterList">
          <Parameter name="variable" type="string" value="surface-surface_subsurface_flux" />
          <Parameter name="region" type="string" value="surface domain" />
          <Parameter name="location name" type="string" value="cell" />
          <Parameter name="functional" type="string" value="extensive integral" />
          <Parameter name="time integrated" type="bool" value="true" />
          <ParameterList name="modifier" type="ParameterList">
            <Parameter name="function type" type="string" value="standard math" />
            <Parameter name="operator" type="string" value="negative" />

However, the estimated groundwater discharge (i.e., positive exfiltration) is higher than watershed runoff, particularly during low flow period (see attached figures).

Does this mean we are double counting some of the exfiltrated flows (e.g., hyporheic flows that go back into the subsurface and then exfiltrate into the surface)? Is it possible to get close to the "true" groundwater discharge?

The watershed we use for the analysis is the Coal Creek.
 
![discharge_ex](https://github.com/amanzi/ats/assets/122495798/bd8d7a12-8a2d-4375-8d2f-468eb11d849d)
![Ex_infiltration](https://github.com/amanzi/ats/assets/122495798/8cc37814-42b0-4cd2-ba1d-883014586914)

I cannot follow up with the conversation because I requested to have access but not accepted yet. 
Thanks for your help.

**Comment by ecoon** [comment]
This sort of thing is better for the user group (clearly, as you haven't gotten a response in a few months, whups!)  Hopefully you got things addressed there.
