### ISSUE TITLE
Deprecate old python2 variants of utils for reading vis files

### ISSUE THREAD

**Issue by banesullivan** [amanzi/ats#41]
https://github.com/amanzi/ats/blob/a97e42238e4397e99d3110c0a147b1e450776947/tools/utils/transect_data.py#L166

Would it be possible to easily update all of the Python code in this repo to Python 3 since Python 2 has officially reached its end of life? Reference https://www.python.org/doc/sunset-python-2/

A good reference for differences: https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html

**Comment by banesullivan** [comment]
I'm hoping it will be as simple as updating a few print statements and that the bulk of the code is okay as is.

Is there a testing routine for the Python code?

**Comment by ecoon** [comment]
Yes, that's probably true.  It is a mix of python2 and python3 at this point -- I've updated them as I use them.  90% of the changes are print statements; the only other gotcha I've run into when converting is changing dictionary method names (e.g. iter* methods in python2 went away, etc).

There is no testing routine for most of the python code -- most of these (all?) are simply my scripts that I developed in visualizing individual runs, and they worked when the plot looked right (or comparable).  Some were refactored into "library" modules, and some became argparse'd scripts, but most are little more than a one-off script.  Some probably don't even work with current output anymore, but if you run into any of these, please let me know and I can fix them or remove them if they are inappropriate.

**Comment by ecoon** [comment]
@banesullivan  Let me know if you intend to update them, or if not, and you have a list of ones you've run into, I can probably knock them out quickly enough.  I'm actually surprised that transect_data.py hasn't been done.  I'd definitely like the demo notebooks to be on python3, and all of the new work done in documenting these has been in python3.

**Comment by ecoon** [comment]
Actually I lied -- these are old.  I was confused because I have updated these already, but I put them in a new place because the notebooks hadn't been updated.

I need to remove/deprecate transect_data.py, mesh.py, and a few others, and then the real work is to update ats-demos and other notebooks to use https://github.com/amanzi/ats/blob/master/tools/utils/ats_xdmf.py instead.  That is intended as a "one stop" tool for visualization of output in python.

**Comment by banesullivan** [comment]
Thanks for chining in, @ecoon! It sounds like the problem code will be deprecated in favor of the new `ats_xdmf` module, correct? I may be able to help with https://github.com/amanzi/ats-demos/issues/3 - will chime in over there

**Comment by ecoon** [comment]
column_data has been updated, transect_data has been removed, and all (nearly all?) demos have been updated to use ats_xdmf.  mesh has been removed.  I think this is complete.
