### ISSUE TITLE
Incorrect space generated for MFD in mpc_permafrost

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#43]
Daniil, I can fix this, but I don't understand the NLFV branch of the code starting from here:

https://github.com/amanzi/ats/blob/7d00e2d24bf4ab7d05fa8f1e5b985abbb30bcfe2/src/pks/mpc/mpc_permafrost.cc#L90
through line 102.

The bug is that when the discretization is MFD, the CVS needs to get FACE, not BOUNDARY_FACE (e.g. at line 98).

But why is this constructed this way?  Should it really be an Operator_FaceCell for NLFV, or should it instead be an Operator_CellBndFace?

**Comment by ecoon** [comment]
Sorry, the link got broken when I pushed the fix.  I updated the link to the old version.

**Comment by ecoon** [comment]
Reopening so Daniil sees this. Please close it if Operator_FaceCell is correct for NLFV.

**Comment by dasvyat** [comment]
Ethan, mpc_permafrost.cc looks OK to me.
