### ISSUE TITLE
Add option for ats to report the version number / git info.

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/ats#5]
There are a number of good reasons to give users an option report the version number and git sha1 hash for a given build.   Amanzi has this functionality, and to get started here we'll leverage that CMake magic that fills in a template in a short header file.

**Comment by jd-moulton** [comment]
Duplicated by #12.  Closing this one assuming Ethan has this going now.

**Comment by ecoon** [comment]
Closed mine as duplicate.  No, I am not working on this.  I started that ticket mainly to ask what you had done in Amanzi, not realizing this was already here.  If there is an easy way to pull Amanzi stuff into ATS, that would be great.

**Comment by ecoon** [comment]
@jd-moulton  is this still in the works?

**Comment by ecoon** [comment]
@jd-moulton Can this be closed?

**Comment by jd-moulton** [comment]
Soon, we just need to decide on what command line options we want and what they show.  ATS builds depend on three things, ATS, Amanzi, and the TPLs collection.   What I put in so far adds --print_version option and gives the following output, 

    ATS Version     1.0-dev_964cd457 
    GIT branch      master
    GIT global hash 964cd457

    Amanzi Version  1.1-dev_b46f54dfa
    GIT branch      master
    GIT global hash b46f54dfa

    ATS::SIMULATION_DID_NOT_RUN

But this may be confusing the average user.  So I'm thinking we should have the following options:

    --print_version
    --print_amanzi_version
    --print_tpl_versions

These are consistent with Amanzi, but also the "print" part seems to be a little verbose.   We could simply have
  
   --version
   --amanzi_version
   --tpl_versions

And we could have a --print_all option?  

Lastly, I removed the "options.xml" default, so if that's used by anyone we should put it back.  Note you request version info and provide an xml input file, the version info is printed out at the beginning of a run.  If you don't provide an xml file, then you see the "ATS::SIMULATION_DID_NOT_RUN" output at the end.   This may be unnecessary or you may want some alternative text here.

**Comment by ecoon** [comment]
I guess my preference would be:

    ats --version     --> ATS version
    ats --version-amanzi      --> Amanzi version
    ats --version-tpls    --> TPLs version
    ats --versions      --> all versions printout?

AND

    ats filename.xml    

should be the same as:

    ats --xml_file=filename.xml

Do we really want to think of the filename as an option?  I don't think so.
