### ISSUE TITLE
OUT OF MEMORY issue in reactive transport with ats-master 

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/ats#55]
Another here just to bring up the issue on Github

With the alternative way that Ahmad provided to workaround the initialization issue #54, I had another error msg related to memory.

A few error msg like (I can provide more details when Cori is back):
*** Error in `/global/home/groups-sw/pc_ideas/amanzi-ats-master-chemistry-0716/amanzi-install-master-Release/bin/ats': double free or corruption (out): 0x0000000002155d00 ***
*** Error in `/global/home/groups-sw/pc_ideas/amanzi-ats-master-chemistry-0716/amanzi-install-master-Release/bin/ats': free(): invalid pointer: 0x000000000236ceb8 ***

Not sure if this is related to the issue Ahmad mentioned "transport boundary condition at the end of simulation, related to memory"

Thanks
Zexuan

**Comment by lipnikov** [comment]
FYI: A similar issue has been fixed in Alquimia_PK.cc on Aug 13.

**Comment by ajkhattak** [comment]
@zexuanxu I just pulled recent amanzi and ats, and will be working on fixing the issues you are seeing for ats reactive transport.

**Comment by zexuanxu** [comment]
@lipnikov thanks for the information! I haven't tried your recent Alquimia_PK.cc, as I was trying to pull and use @ajkhattak 's previous commits to workaround the initialization issue, which comes before the "OUT OF MEMORY" issue. I will test after we resolve the initialization issue - hope it resolves.

@ajkhattak thanks!

**Comment by ajkhattak** [comment]
@zexuanxu I was actually talking about the following issue. I run into deallocation issue at the end of ATS reactive transport simulation. A snippet of the backtrace is below. 
@lipnikov Any thoughts?

#13 0x00002aaab3e14852 in Teuchos::RCP<Amanzi::Transport::TransportDomainFunction>::~RCP (this=0xa815c0, __in_chrg=<optimized out>)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/install-1.0.0-alquimia/openmpi-1.10.3/Debug/trilinos-12-18-55a7599733-Nov11/lib/cmake/Epetra/../../../include/Teuchos_RCP.hpp:305
#14 0x00002aaab3e2e30b in std::_Destroy<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction> > (__pointer=0xa815c0)
    at /software/dev_tools/swtree/cs400_centos7.2_pe2016-08/gcc/5.3.0/centos7.2_gcc4.8.5/include/c++/5.3.0/bits/stl_construct.h:93
#15 0x00002aaab3e29575 in std::_Destroy_aux<false>::__destroy<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction>*> (
    __first=0xa815c0, __last=0xa815f0)
    at /software/dev_tools/swtree/cs400_centos7.2_pe2016-08/gcc/5.3.0/centos7.2_gcc4.8.5/include/c++/5.3.0/bits/stl_construct.h:103
#16 0x00002aaab3e23bf4 in std::_Destroy<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction>*> (__first=0xa815c0, __last=0xa815f0)
    at /software/dev_tools/swtree/cs400_centos7.2_pe2016-08/gcc/5.3.0/centos7.2_gcc4.8.5/include/c++/5.3.0/bits/stl_construct.h:126
#17 0x00002aaab3e18eef in std::_Destroy<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction>*, Teuchos::RCP<Amanzi::Transport::TransportDomainFunction> > (__first=0xa815c0, __last=0xa815f0)
    at /software/dev_tools/swtree/cs400_centos7.2_pe2016-08/gcc/5.3.0/centos7.2_gcc4.8.5/include/c++/5.3.0/bits/stl_construct.h:151
#18 0x00002aaab3e124e5 in std::vector<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction>, std::allocator<Teuchos::RCP<Amanzi::Transport::TransportDomainFunction> > >::~vector (this=0x9da3a8, __in_chrg=<optimized out>)
    at /software/dev_tools/swtree/cs400_centos7.2_pe2016-08/gcc/5.3.0/centos7.2_gcc4.8.5/include/c++/5.3.0/bits/stl_vector.h:424
#19 0x00002aaab46fbb9a in Amanzi::Transport::Transport_PK_ATS::~Transport_PK_ATS (this=0x9d9e60, __in_chrg=<optimized out>,
    __vtt_parm=<optimized out>)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0.0-alquimia/src/physics/ats/src/pks/transport/Transport_PK_ATS.hh:78
#20 0x00002aaab46fbfaa in Amanzi::Transport::Transport_PK_ATS::~Transport_PK_ATS (this=0x9d9e60, __in_chrg=<optimized out>,
    __vtt_parm=<optimized out>)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi/repos/1.0.0-alquimia/src/physics/ats/src/pks/transport/Transport_PK_ATS.hh:78
#21 0x00002aaab86043cf in Teuchos::DeallocDelete<Amanzi::PK>::free (this=0x9e43e8, ptr=0x9da930)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/install-1.0.0-alquimia/openmpi-1.10.3/Debug/trilinos-12-18-55a7599733-Nov11/lib/cmake/Epetra/../../../include/Teuchos_RCPDecl.hpp:1008
#22 0x00002aaab8603a96 in Teuchos::RCPNodeTmpl<Amanzi::PK, Teuchos::DeallocDelete<Amanzi::PK> >::delete_obj (this=0x9e43c0)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/install-1.0.0-alquimia/openmpi-1.10.3/Debug/trilinos-12-18-55a7599733-Nov11/lib/cmake/Epetra/../../../include/Teuchos_RCPNode.hpp:614
#23 0x00000000004d1e38 in Teuchos::RCPNodeHandle::unbind (this=0x9daa10)
    at /software/user_tools/current/cades-ccsi/ats_ajc/amanzi-tpls/install-1.0.0-alquimia/openmpi-1.10.3/Debug/trilinos-12-18-55a7599733-Nov11/lib/cmake/Teuchos/../../../include/Teuchos_RCPNode.hpp:1069

**Comment by zexuanxu** [comment]
@ajkhattak it seems your error msg is different from mine and happens at the end of the simulation? My simulation does not even start...Well I'm actually going to submit a new issue for the error msg I had in ats-demos 08_integrated_hydro_transport case, which has flow and transport only (no geochemistry).

**Comment by lipnikov** [comment]
what I fixed recently was related to a deallocation error.

**Comment by ajkhattak** [comment]
okay, I pulled on August 18th, so I think I have your changes.

**Comment by lipnikov** [comment]
Did valgrind report any memory corruption before the crash?

**Comment by ecoon** [comment]
closing with complete refactor of this -- we can reopen if they show up again.
