### ISSUE TITLE
Segmentation fault/Address not mapped issue for ats-demos (master) 08_integrated_hydro_transport

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/ats#57]
I was just trying to test if the flow/transport only (no geochemistry) is working so I run the ats-demos (master branch) 08_integrated_hydro_transport. The error msg is below. I slightly tweak the input file for the latest master build. Not sure if this indicates that transport needs to double check...

  1 ASCEMIO_Info: Preferred group size is set to nprocs/numIOgroups (1/1)
  2 ASCEMIO_Info: Preferred group size is set to 1
  3 ASCEMIO_Info: Preferred group size is set to nprocs/numIOgroups (1/1)
  4 ASCEMIO_Info: Preferred group size is set to 1
  5 [n0082:80828] *** Process received signal ***
  6 [n0082:80828] Signal: Segmentation fault (11)
  7 [n0082:80828] Signal code: Address not mapped (1)
  8 [n0082:80828] Failing at address: 0x6786
  9 [n0082:80828] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2b1a06b23630]

**Comment by ecoon** [comment]
I'm still revamping transport.  Please be patient.
