### ISSUE TITLE
issues in coupling for integrated transport

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#65]
Some tests have made it clear that there are some issues in the implementation of coupling surface and subsurface transport.

Specifically two main issues, each with a test problem.

1. (the potentially less important one) -- In the case of no flow between the surface and subsurface, molecular diffusion of components across the surface-subsurface interface should still exist.  Currently, all coupling between surface and subsurface water is handled via the advective term, so if there is no water flux, there is no component flux.

This is demonstrated in test: https://github.com/amanzi/ats-regression-tests/blob/ecoon/pk_cleanup/06_transport/transport-column_diffusion.xml 

In this test, the problem is initialized as hydrostatic with a head of 1m above the surface, and the boundary conditions are all 0 Neumann, and there are no sources.  The solution is 0 mass flux on all faces of both the surface and subsurface.  The surface is initialized with concentration 1 of a tracer.  The subsurface is initialized with a concentration of 0.  The molecular diffusion is artificially cranked to a large value.  After solving to a sufficiently large time, it is clear that the subsurface concentration is still identically 0 and the surface concentration is still identically 1.

2. (the more important one) -- In the case of integrated surface and subsurface, flow and transport, we must deal with the case where a surface source of water (e.g. rainfall) comes with a nonzero concentration of component X (e.g. Sulfer dioxide, NOX), but there is no surface water.  

The flow coupling in this case is correctly done -- the surface input of water (rainfall rate) is balanced by a mass flux from surface to subsurface that is used as both a sink from the surface equation and a Neumann BC on the subsurface equation.  This Neumann-coupling condition correctly reduces to (when solved implicitly) an algebraic equation on the surface (0 = dWC/dt = Q_rain - Q_subsurface_to_suface) and a Neumann BC on the subsurface (q_out = Q_subsurface_to_surface = -Q_rain).

Unfortunately the transport equation is not correct (at least in the donor upwind case).  Currently the coupling from surface to subsurface is done through the advective term, where a Dirichlet concentration is multiplied by a face-based mass flux of water (e.g. in the donor upwind case).  But the explicit transport equation is hard-coded such that the concentration, which gets used at the Dirichlet condition, is 0 when there is no water on the surface (see https://github.com/amanzi/ats/blob/ecoon/pk_cleanup/src/pks/transport/transport_ats_pk.cc#L1316 ).

So while water comes in, as long as there is no surface water, no component concentration comes in.

This is demonstrated in test: https://github.com/amanzi/ats-regression-tests/blob/ecoon/pk_cleanup/06_transport/transport-column_infiltration.xml 

In this test, the problem is initialized with a hydrostatic head below the surface, e.g. no surface water.  A source of water is provided to the surface flow equation, and a source of component Tracer1 is provided to the surface transport equation, given by a concentration of 1 times the source of water.  (Note, this is another ticket that needs to be fixed, we need a way to specify the concentration of source, not the product.).   In this run, one would expect the  surface water to stay at 0 until the subsurface fills up, but that the source of Tracer show up in the subsurface immediately.

Note this is more general than just the case of rain.  It also affects the case where, for instance, lateral overland flow brings water from upstream onto a surface cell that immediately infiltrates.  In this case as well, the ponded depth (and therefore the water content) on the surface is identically zero, but in this case the source delivered to the subsurface should be the product of the uphill concentration and the exchange flux of water.  So it is not as simple as just getting the right concentration -- it really needs to be that the sum of all other sources in the surface transport equation is balanced by the surface-subsurface exchange flux of component X.  This could be done either by specifying the flux of X (which would then have to be moved into the advective term) or by first calculating the balance, then dividing by the water exchange flux to get an effective concentration of that incoming water, and then using the same Dirichlet approach.

**Comment by ecoon** [comment]
@dasvyat Can you comment on these?  Are they known issues with the transport coupling or am I missing something here?  I will add tests with the higher-order transport as opposed to the donor upwind, not sure if that will change things (since the boundary term for a DomainFunctionCoupling is used in different places for each advection scheme).

**Comment by jd-moulton** [comment]
I'll pose as @dasyvat to move the discussion forward a bit.  Here's my understanding:

1.  This lack of molecular diffusion between surface and subsurface is known, and relates to the need for additional code to form this global surface/subsurface system to solve the coupled diffusion problem.   On the list of things that we'd like to do.  Need to agree on priority and layout a plan for someone to implement it.

1.  I think @dasvyat tested this case.  It's definitely something that was considered as were cases when there is ponded water and the rain water mixes adjusting the concentration of the water that is infiltrating.   So best I can say here is we need to have @dasvyat weigh in on the current tests and what the design includes.

**Comment by dasvyat** [comment]
Issue 1: Yes, this is a known issue. As David mentioned currently we don't form a global matrix for integrated transport (in explicit case, ATS currently relies on explicit formulation). So there is no diffusion across surface/subsurface interface. I think, we can resolve this issue mimicking implicit implementation in ATS.

Issue 2: The issue with rainfall is more vivid when water infiltrates immediately into subsurface, so for transport component X  never appears on the surface. It was solved in 0.87 version using a special copy of the concentration vector which includes mixing source concentrations in advance. So special settings in the input file are required. I'll take a look wat it transferred correctly during the merge.

**Comment by lipnikov** [comment]
1. You may consider solving diffusion equation in each domain using Robin BCs to account for coupling.

**Comment by ecoon** [comment]
> Issue 2: The issue with rainfall is more vivid when water infiltrates immediately into subsurface, so for transport component X never appears on the surface. It was solved in 0.87 version using a special copy of the concentration vector which includes mixing source concentrations in advance. So special settings in the input file are required. I'll take a look wat it transferred correctly during the merge.

That's exactly what I was thinking of for a fix, so sounds like we're on the same page here.  Let me know what you find -- I was hoping to hear it was a case of not having the right parameters set.

**Comment by ecoon** [comment]
Looking at the demos repo, I'm guessing this might be the answer?

https://github.com/amanzi/ats-demos/blob/ats-demos-0.87/12_integrated_hydro_transport/integrated_hydro_transport_with_rain_src.xml#L388

**Comment by ecoon** [comment]
Ok, I think this works now?  Still may not deal with the case that the concentration is coming from upstream and not from rainfall?  It may be worth looking into a more general way of doing this -- you effectively _have_ the total sum of sources stored in the overland advance, but then you ignore it and zero out the concentration.  Rather than doing this sum twice, it seems that we could just make sure the boundary coupling is done last, and save the value then.  This obviously requires that surface transport is done first, but that is how flow is done too.

**Comment by zexuanxu** [comment]
I just tested and do NOT think the source term in transport and chemistry work well. If I commented out "boundary conditions" under subsurface transport PK and "source terms" under surface transport, the code seems to run (although it hit another error msg with NaN in solid_qty term, which might be another issue). The error msg is "required parameter "regions" is missing" in the plist.keyword(boundary condition function) - I print them out to identify where the error msg comes from. So I'm assuming some hierarchy in the boundary condition might be run? I'm coping my "boundary conditions" under subsurface transport and "source terms" under surface transport - which was implemented about a year ago and was working well with modif4chemistry-0.87.

      <ParameterList name="boundary conditions" type="ParameterList">
        <ParameterList name="concentration" type="ParameterList">
          <ParameterList name="coupling" type="ParameterList">
            <ParameterList name="BC coupling" type="ParameterList">
              <Parameter name="spatial distribution method" type="string" value="domain coupling" />
              <Parameter name="submodel" type="string" value="field" />
              <Parameter name="regions" type="Array(string)" value="{surface domain}" />
              <ParameterList name="boundary concentration" type="ParameterList">
                <Parameter name="field_out_key" type="string" value="surface-total_component_concentration" />
                <Parameter name="copy_field_out_key" type="string" value="with source" />
              </ParameterList>
            </ParameterList>
          </ParameterList>
        </ParameterList>
      </ParameterList>


      <ParameterList name="source terms" type="ParameterList">
        <ParameterList name="concentration" type="ParameterList">
          <ParameterList name="coupling" type="ParameterList">
            <ParameterList name="Surface" type="ParameterList">
              <Parameter name="regions" type="Array(string)" value="{surface domain}" />
              <Parameter name="spatial distribution method" type="string" value="domain coupling" />
              <Parameter name="submodel" type="string" value="rate" />
              <ParameterList name="sink" type="ParameterList">
                <Parameter name="flux_key" type="string" value="mass_flux" />
                <Parameter name="copy_flux_key" type="string" value="next_timestep" />
                <Parameter name="field_out_key" type="string" value="total_component_concentration" />
                <Parameter name="copy_field_out_key" type="string" value="default" />
                <Parameter name="field_in_key" type="string" value="surface-total_component_concentration" />
                <Parameter name="copy_field_in_key" type="string" value="with source" />
              </ParameterList>
            </ParameterList>
          </ParameterList>
        </ParameterList>
      </ParameterList>

**Comment by ecoon** [comment]
You don't have the current hierarchy of lists.  Either base your example off of the one that works in ats-regression tests under reactive transport on ecoon/pk_cleanup or wait til I provide an input spec convertor.  That is the _only_ one that currently works.  Your old files will not work.

**Comment by ecoon** [comment]
closed in #64
