### ISSUE TITLE
Fix "blacklist" for NOT writing variables into visualization file

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/ats#73]
For some reason, the "blacklist" feature does not work for selecting variables that we do NOT want to write into the visualization file. 

It worked well previously, but I'm not sure why or when it doesn't work for now.
This is what I had for testing (which works in the past), under ParameterList"state"

<Parameter name="blacklist" type="Array(string)" value="{alquimia_aux*, free_ion*, primary*, secondary*, total_component_quantity.*, solid*, ion_exchange_ref*, mineral_reaction*, mineral_specific*}"/>

I noticed that Danill has addressed this in the past
8a87b709819ffc5e851a7d370d4e9b4819089aa9

**Comment by ecoon** [comment]
It looks like the following needs to be done:

There is a method in Amanzi::State called InitializeIOFlags_() (or something close) -- this method needs to be made public instead of protected.

Then, a call to that method should be added to ATS's coordinator in Initialize -- see State::Initialize() for where it fits in context to the other Initialize methods called there.

**Comment by lipnikov** [comment]
I made the method public yesterday in Amanzi, when I looked at the problem from Amanzi's angle, see the last commit.

**Comment by zexuanxu** [comment]
It seems Konstantin's updates are not sufficient to make this work for ATS. 

I incorporated Konstantin's updates and added "S_->InitializeIOFlags_();" in the ATS's coordinator (I don't know why Danill's commit shows where it should be but does not exist in the latest commit anymore), but it still does not work immediately.

Is there anywhere else I need to add? I can help look into it more.

**Comment by lipnikov** [comment]
InitializeIOFlags_() is better to be called after the PK and State were initialized. This is the only reasonable requirement I can think of. Also, this routine is a part of State::Initialize(); hence, there is no need to call it in all initialization algorithms.

**Comment by ecoon** [comment]
ATS doesn't call State::Initialize, because of the order issue.  Instead it calls the components individually.

Agreed that it should get called after PK and the rest of the state initialization stuff though.

If it is public, it should lose the trailing underscore in Amanzi though.

**Comment by lipnikov** [comment]
I can drop underscore and update both ATS and Amanzi now without a PR if you do not mind.

**Comment by dasvyat** [comment]
I suggest let Konstantin add this feature to ATS  without PR.

________________________________

**Comment by zexuanxu** [comment]
@lipnikov Just let you know that adding IO flags seems not sufficient to resolve this issue.

**Comment by zexuanxu** [comment]
I believe this issue has been fixed in the master.
