### ISSUE TITLE
Feature Request: Rule for Access to "Initial Condition" parameter list by Subgrids/Domain-sets 

### ISSUE THREAD

**Issue by SaubhagyaGT** [amanzi/ats#79]
In the current code, it appears that parameters provided in the "initial conditions" parameter list under State list cannot be assigned to Subgrids/Domain-sets. For example, "Isotherm_Kd" parameter list to implement equilibrium sorption is provided under "initial conditions" parameter list (under State), thus are not applied to subgrids. Is it possible to have a rule like "subgrid_*-Isotherm_Kd" to assign certain parameters in the "initial conditions" list to be assigned to subgrids?

If most parameters in the "initial conditions" parameter list are not relevant to subgrids and "Isotherm_Kd" is an exception, may be "Isotherm_Kd" can be moved under State or PK lists. There might be other concerns with this option.

**Comment by ecoon** [comment]
Has @ajkhattak looked at this yet?

**Comment by ecoon** [comment]
Actually, my mistake -- this is not an ATS problem, but an Amanzi one.  See the ticket here:

https://github.com/amanzi/amanzi/issues/533
