### ISSUE TITLE
change all default sources currently called "mass_source" to "water_source" or "water_mass_source"

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#83]
There has been endless confusion in using the water source in the transport PK due to the default name, "mass_source".  This is actually the mass of _water_, not the mass of component C.  

I propose to change all mass_source defaults, currently in Richards, overland flow, all other flow PKs, and transport which uses this evaluator to "water_source".  @dasvyat will this cause any of the LANL flow PKs trouble (thinking shallow water or others?)

**Comment by dasvyat** [comment]
I don't think it will cause any issues if the default name will be changed in all PKs.

**Comment by ecoon** [comment]
Went to do this but it looks like you've already done it, thanks.  I'll update the xml conversion script unless you've already done that too?

**Comment by dasvyat** [comment]
I have updated the regression test input files but I didn't update the conversion script
